atlas_org_id = "<UPDATE WITH YOUR ORG ID>"
atlas_project_name = "yourProjectName"
environment = "dev"
cluster_instance_size_name = "M20"
cloud_provider = "GCP"
atlas_region = "asia-south1"
mongodb_version = "7.0"
ip_address = "<UPDATE WITH YOUR IP>"